// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HardwareInfo: typeof import('./src/components/hardware/HardwareInfo.vue')['default']
    HardwareItem: typeof import('./src/components/hardware/HardwareListItem.vue')['default']
    HardwareList: typeof import('./src/components/hardware/HardwareList.vue')['default']
    HardwareListItem: typeof import('./src/components/hardware/HardwareListItem.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NH1: typeof import('naive-ui')['NH1']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
