// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppNav: typeof import('./src/components/nav/AppNav.vue')['default']
    FadeSlideTransition: typeof import('./src/components/transition/FadeSlideTransition.vue')['default']
    FadeTransition: typeof import('./src/components/transition/FadeTransition.vue')['default']
    HardwareDetails: typeof import('./src/components/hardware/HardwareDetails.vue')['default']
    HardwareInfo: typeof import('./src/components/hardware/HardwareInfo.vue')['default']
    HardwareItem: typeof import('./src/components/hardware/HardwareListItem.vue')['default']
    HardwareList: typeof import('./src/components/hardware/HardwareList.vue')['default']
    HardwareListItem: typeof import('./src/components/hardware/HardwareListItem.vue')['default']
    HardwarePriceMessage: typeof import('./src/components/hardware/HardwarePriceMessage.vue')['default']
    HardwareViewAside: typeof import('./src/components/hardware/HardwareViewAside.vue')['default']
    HardwareViewForm: typeof import('./src/components/hardware/HardwareViewForm.vue')['default']
    HardwareViewHeader: typeof import('./src/components/hardware/HardwareViewHeader.vue')['default']
    HardwareViewListAside: typeof import('./src/components/hardware/HardwareViewListAside.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopConfirm: typeof import('naive-ui')['NPopConfirm']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PopConfirmDelete: typeof import('./src/components/base/PopConfirmDelete.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheTransition: typeof import('./src/components/transition/TheTransition.vue')['default']
  }
}

export { }
